name: Debug secrets
on: [push]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets length
        run: |
          echo "HOST length: ${#SSH_HOST}"
          echo "USER length: ${#SSH_USER}"
          echo "PORT length: ${#SSH_PORT}"
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
